### ISSUE TITLE
Hosting error

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited-Noclient#4]
I use hamachi for host server, my friends can not come in and they're disabled firewall and are in my network more when sending the link for them to play example "http://agar.io/?ip=(hamachi ipv4):(serverport)"they say they can not enter,i use vannila agar.io.
_Sorry bad inglish._

**Comment by LegitSoulja** [comment]
This repo of OgarUnlimited doesn't work with agar.io. You should try this instead

http://play.ogarul.tk/?ip=(hamachi ipv4):(serverport)

**Comment by GhostShot3** [comment]
@LegitSoulja Oks,Thanks LegitSouja.

**Comment by LegitSoulja** [comment]
@GhostShot3 I'm sorry, I wasn't paying attention. 

This is the no client, which can be used with agar.io, but I don't know if it still works or not.
